{% set name = "aiida-bigdft" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aiida-bigdft-{{ version }}.tar.gz
  sha256: a9d13a9f6fc9830446f5a9a8f066bae28f21b667cb531c8b105e51b265bc1af1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - reentry
  run:
    - aiida-core >=1.1.1,<2.0.0
    - python >={{ python_min }}
    - six
    - voluptuous

test:
  imports:
    - aiida_bigdft
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/BigDFT-group/aiida-bigdft-plugin
  summary: Aiida plugin for BigDFT code
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisjsewell
